-- Create users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  auth_id uuid unique not null,
  name text,
  email text,
  phone text,
  role text,
  status text check (status in ('approved', 'pending')) default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Safely add columns if they are missing (for existing tables)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name='users' and column_name='auth_id') then
    alter table users add column auth_id uuid unique not null;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='users' and column_name='name') then
    alter table users add column name text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='users' and column_name='email') then
    alter table users add column email text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='users' and column_name='phone') then
    alter table users add column phone text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='users' and column_name='role') then
    alter table users add column role text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='users' and column_name='status') then
    alter table users add column status text check (status in ('approved', 'pending')) default 'pending';
  end if;
end $$;

-- Create menu_items table
create table if not exists menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price decimal not null,
  status text check (status in ('approved', 'pending')) default 'pending',
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

do $$
begin
  if not exists (select 1 from information_schema.columns where table_name='menu_items' and column_name='status') then
    alter table menu_items add column status text check (status in ('approved', 'pending')) default 'pending';
  end if;
  if not exists (select 1 from information_schema.columns where table_name='menu_items' and column_name='image_url') then
    alter table menu_items add column image_url text;
  end if;
  -- Ensure other columns too just in case
end $$;

-- Create inventory_items table
create table if not exists inventory_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  current_stock decimal not null default 0,
  min_stock decimal not null default 0,
  unit text not null,
  last_restocked timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create purchases table
create table if not exists purchases (
  id bigint generated by default as identity primary key,
  purchase_type text check (purchase_type in ('inventory', 'other')) not null,
  item_name text not null,
  category text not null,
  quantity decimal not null,
  unit text not null,
  total_price decimal not null,
  supplier text,
  assigned_to text not null,
  purchase_date date not null,
  receipt_photo text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

do $$
begin
  if not exists (select 1 from information_schema.columns where table_name='purchases' and column_name='assigned_to') then
    alter table purchases add column assigned_to text not null default 'Manager';
  end if;
  -- Add other purchase columns if missing
end $$;

-- Create restaurant_tables table
create table if not exists restaurant_tables (
  id bigint generated by default as identity primary key,
  table_number integer not null unique,
  capacity integer not null,
  status text check (status in ('available', 'occupied', 'reserved', 'maintenance')) default 'available',
  location text,
  current_order_id bigint, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create orders table
create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  table_id bigint references restaurant_tables(id),
  customer_name text,
  status text check (status in ('pending', 'preparing', 'ready', 'served', 'completed', 'cancelled')) default 'pending',
  total_amount decimal not null default 0,
  is_paid boolean default false,
  transaction_id text,
  payment_method text,
  completed_time timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add foreign key for restaurant_tables.current_order_id
do $$
begin
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'restaurant_tables_current_order_id_fkey') then
    alter table restaurant_tables add constraint restaurant_tables_current_order_id_fkey foreign key (current_order_id) references orders(id);
  end if;
end $$;

-- Create order_items table
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) not null,
  menu_item_name text not null,
  quantity integer not null,
  unit_price decimal not null,
  total_price decimal not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table users enable row level security;
alter table menu_items enable row level security;
alter table inventory_items enable row level security;
alter table purchases enable row level security;
alter table restaurant_tables enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

-- Create policies (drop first to avoid error if exists)
drop policy if exists "Enable all access for authenticated users" on users;
create policy "Enable all access for authenticated users" on users for all using (auth.role() = 'authenticated');

drop policy if exists "Enable all access for authenticated users" on menu_items;
create policy "Enable all access for authenticated users" on menu_items for all using (auth.role() = 'authenticated');

drop policy if exists "Enable all access for authenticated users" on inventory_items;
create policy "Enable all access for authenticated users" on inventory_items for all using (auth.role() = 'authenticated');

drop policy if exists "Enable all access for authenticated users" on purchases;
create policy "Enable all access for authenticated users" on purchases for all using (auth.role() = 'authenticated');

drop policy if exists "Enable all access for authenticated users" on restaurant_tables;
create policy "Enable all access for authenticated users" on restaurant_tables for all using (auth.role() = 'authenticated');

drop policy if exists "Enable all access for authenticated users" on orders;
create policy "Enable all access for authenticated users" on orders for all using (auth.role() = 'authenticated');

drop policy if exists "Enable all access for authenticated users" on order_items;
create policy "Enable all access for authenticated users" on order_items for all using (auth.role() = 'authenticated');
